kind: Deployment
apiVersion: apps/v1

metadata:
  name: nova-api
  labels:
    system: openstack
    type: api
    component: nova
spec:
  replicas: {{ if not .Values.pod.debug.api }}{{ .Values.pod.replicas.api }}{{ else }} 1 {{ end }}
  revisionHistoryLimit: {{ .Values.pod.lifecycle.upgrades.deployments.revision_history }}
  strategy:
    type: {{ .Values.pod.lifecycle.upgrades.deployments.podReplacementStrategy }}
    {{ if eq .Values.pod.lifecycle.upgrades.deployments.podReplacementStrategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.pod.lifecycle.upgrades.deployments.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.pod.lifecycle.upgrades.deployments.rollingUpdate.maxSurge }}
    {{ end }}
  selector:
    matchLabels:
      name: nova-api
  template:
    metadata:
      labels:
        name: nova-api
{{ tuple . "nova" "api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.defaults.default.graceful_shutdown_timeout | add 5 }}
{{- if .Values.pod.debug.api }}
      securityContext:
        runAsUser: 0
{{- end }}
{{ tuple . "nova" "api" | include "kubernetes_pod_anti_affinity" | indent 6 }}
      containers:
        - name: nova-api
          image: {{ required ".Values.global.registry is missing" .Values.global.registry}}/ubuntu-source-nova-api:{{.Values.imageVersionNovaApi | default .Values.imageVersionNova | default .Values.imageVersion | required "Please set nova.imageVersion or similar"}}
          imagePullPolicy: IfNotPresent
          command:
            - dumb-init
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "{{ if .Values.api.use_uwsgi }}uwsgi --ini /etc/nova/api_uwsgi.ini{{ else }}nova-api{{ end }}"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "nova-migration"
            - name: DEPENDENCY_SERVICE
            {{- if eq .Values.mariadb.enabled true }}
              value: "{{ .Release.Name }}-mariadb,{{ .Release.Name }}-api-mariadb,{{ .Release.Name }}-rabbitmq"
            {{- else }}
              value: "{{ .Release.Name }}-postgresql,{{ .Release.Name }}-rabbitmq"
            {{- end }}
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
{{- if .Values.python_warnings }}
            - name: PYTHONWARNINGS
              value: {{ .Values.python_warnings | quote }}
{{- end }}
            - name: PGAPPNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
{{- if not .Values.pod.debug.api }}
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.global.novaApiPortInternal}}
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{.Values.global.novaApiPortInternal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
{{- end }}
          {{- if .Values.pod.resources.api }}
          resources:
{{ toYaml .Values.pod.resources.api | indent 12 }}
          {{- end }}
          ports:
            - name: nova-api
              containerPort: {{.Values.global.novaApiPortInternal}}
          volumeMounts:
            - name: nova-etc
              mountPath: /etc/nova
            - name: nova-bin
              mountPath: /var/lib/kolla/venv/bin
        - name: statsd
          image: prom/statsd-exporter:v0.8.1
          imagePullPolicy: IfNotPresent
          args: [ --statsd.mapping-config=/etc/statsd/statsd-exporter.yaml ]
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{.Values.portMetrics}}
          volumeMounts:
            - name: statsd
              mountPath: /etc/statsd
      volumes:
        - name: nova-etc
          projected:
            defaultMode: 420
            sources:
              - configMap:
                  items:
                    - key: nova.conf
                      path: nova.conf
                    - key: nova-api.conf
                      path: nova-api.conf
                    - key: api-paste.ini
                      path: api-paste.ini
                  {{- if .Values.api.use_uwsgi }}
                    - key: api_uwsgi.ini
                      path: api_uwsgi.ini
                  {{- end}}
                  {{- if .Values.audit.enabled }}
                    - key: nova_audit_map.yaml
                      path: nova_audit_map.yaml
                  {{- end}}
                    - key: policy.json
                      path: policy.json
                    - key: logging.ini
                      path: logging.ini
                    - key: rootwrap.conf
                      path: rootwrap.conf
                    - key: api-metadata.filters
                      path: rootwrap.d/api-metadata.filters
                  {{- if .Values.watcher.enabled }}
                    - key: watcher.yaml
                      path: watcher.yaml
                  {{- end }}
                  name: nova-etc
        - name: nova-bin
          projected:
            defaultMode: 0755
            sources:
              - configMap:
                  items:
                    - key: iptables-restore.mock
                      path: iptables-restore
                  name: nova-etc
        - name: statsd
          projected:
            defaultMode: 420
            sources:
              - configMap:
                  items:
                    - key: statsd-exporter.yaml
                      path: statsd-exporter.yaml
                  name: nova-etc
